### ISSUE TITLE
React does not recognize the `backdropDismiss` prop

### ISSUE THREAD

**Issue by puku0x** [ionic-team/ionic-react-test-utils#1]
Thank you Ionic team for providing a useful library for `@ionic/react`!

I faced the following warning when I tested a modal component.
```bash
 ● Console

    console.error node_modules/react-dom/cjs/react-dom.development.js:530
      Warning: React does not recognize the `backdropDismiss` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `backdropdismiss` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
          in div (created by MockControllerInner)
          in MockControllerInner (created by ForwardRef)
          in ForwardRef
          in Unknown
```
```tsx
import React, { FunctionComponent } from 'react';
import { IonModal } from '@ionic/react';

type Props = {
  show: boolean;
  onDidDismiss?: () => void;
};

export const Modal: FunctionComponent<Props> = props => {
  const { show, onDidDismiss, children } = props;

  return (
    <IonModal isOpen={show} backdropDismiss={false} onDidDismiss={onDidDismiss}>
      {show && children}
    </IonModal>
  );
};
```
```tsx
import React from 'react';
import { render } from '@testing-library/react';
import { Modal } from './Modal';

describe('Modal', () => {
  it('render', () => {
    const { asFragment } = render(
      <Modal show>
        <p>content</p>
      </Modal>
    );

    expect(asFragment()).toMatchSnapshot();
  });
});
```

Is it because of missing `backdropDismiss` prop in `mockController`?.

**Comment by elylucas** [comment]
Thanks for the issue!  I just published 0.0.3, which includes some missing props to the controller elements like Modal. If that doesn't fix the issue let me know.

**Comment by puku0x** [comment]
@elylucas Thank you for your quick response. I will try it later.

**Comment by OPerel** [comment]
Hello,
I'm using v 0.0.3 and I'm still getting this warning.

Thanks a lot!

**Comment by wendyperalta** [comment]
I'm also in version 0.0.3 and still getting the same warning in my tests.

**Comment by OPerel** [comment]
Hey @elylucas, any updates on this issue?

**Comment by menachem-stratfs** [comment]
Hey @elylucas, I've still been experiencing this issue on 0.0.3 with the `backdropDismiss` props as well as a few others

I've opened a PR that should fix it - https://github.com/ionic-team/ionic-react-test-utils/pull/31

Thank you for all your hard work in maintaining this crucial package!
